FORMAT: 1A

# Demo API

# Products [/api/products]
Product object representation

## Get products [GET /api/products]
Get a list of products

+ Request (application/json)

+ Response 200 (application/json)
    + Body

            [
                {
                    "id": 1,
                    "name": "Purple widget",
                    "description": "A purple widget",
                    "price": 5.99,
                    "attributes": "{\"colour\": \"Purple\",\"size\": \"Small\"}",
                    "created_at": "*",
                    "updated_at": "*"
                }
            ]

## Get a product [GET /api/products/1]
Get a single product

+ Request (application/json)

+ Response 200 (application/json)
    + Body

            {
              "id": 1,
              "name": "Purple widget",
              "description": "A purple widget",
              "price": 5.99,
              "attributes": "{\"colour\": \"Purple\",\"size\": \"Small\"}",
              "created_at": "*",
              "updated_at": "*"
            }

## Create products [POST /api/products]
Create a new product

+ name (string) - The product name
+ description (string) - The product description
+ price (float) - The product price
+ attributes (string) - The product attributes

+ Request (application/json)
    + Body

            {
                "name": "Blue widget",
                "description": "A blue widget",
                "price": 5.99,
                "attributes": "{\"colour\": \"blue\",\"size\": \"Small\"}"
            }

+ Response 201 (application/json)
    + Body

            {
              "id": 2,
              "name": "Blue widget",
              "description": "A blue widget",
              "price": 5.99,
              "attributes": "{\"colour\": \"blue\",\"size\": \"Small\"}",
              "created_at": "*",
              "updated_at": "*"
            }
